export enum KeyboardEventCode {
    Backquote = 'Backquote', // `~ on a US keyboard
    Backslash = 'Backslash', // Used for both the US \| (on the 101-key layout) and also for the key located between the " and Enter keys on row C of the 102-, 104- and 106-key layouts. Labelled #~ on a UK (102) keyboard
    BracketLeft = 'BracketLeft', // [{ on a US keyboard
    BracketRight = 'BracketRight', // ]} on a US keyboard
    Comma = 'Comma', // ,< on a US keyboard
    Digit0 = 'Digit0', // 0) on a US keyboard
    Digit1 = 'Digit1', // 1! on a US keyboard
    Digit2 = 'Digit2', // 2@ on a US keyboard
    Digit3 = 'Digit3', // 3# on a US keyboard
    Digit4 = 'Digit4', // 4$ on a US keyboard
    Digit5 = 'Digit5', // 5% on a US keyboard
    Digit6 = 'Digit6', // 6^ on a US keyboard
    Digit7 = 'Digit7', // 7& on a US keyboard
    Digit8 = 'Digit8', // 8* on a US keyboard
    Digit9 = 'Digit9', // 9( on a US keyboard
    Equal = 'Equal', //=+ on a US keyboard
    KeyA = 'KeyA', // a on a US keyboard
    KeyB = 'KeyB', // b on a US keyboard
    KeyC = 'KeyC', // c on a US keyboard
    KeyD = 'KeyD', // d on a US keyboard
    KeyE = 'KeyE', // e on a US keyboard
    KeyF = 'KeyF', // f on a US keyboard
    KeyG = 'KeyG', // g on a US keyboard
    KeyH = 'KeyH', // h on a US keyboard
    KeyI = 'KeyI', // i on a US keyboard
    KeyJ = 'KeyJ', // j on a US keyboard
    KeyK = 'KeyK', // k on a US keyboard
    KeyL = 'KeyL', // l on a US keyboard
    KeyM = 'KeyM', // m on a US keyboard
    KeyN = 'KeyN', // n on a US keyboard
    KeyO = 'KeyO', // o on a US keyboard
    KeyP = 'KeyP', // p on a US keyboard
    KeyQ = 'KeyQ', // q on a US keyboard
    KeyR = 'KeyR', // r on a US keyboard
    KeyS = 'KeyS', // s on a US keyboard
    KeyT = 'KeyT', // t on a US keyboard
    KeyU = 'KeyU', // u on a US keyboard
    KeyV = 'KeyV', // v on a US keyboard
    KeyW = 'KeyW', // w on a US keyboard
    KeyX = 'KeyX', // x on a US keyboard
    KeyY = 'KeyY', // y on a US keyboard
    KeyZ = 'KeyZ', // z on a US keyboard
    Minus = 'Minus', // -_ on a US keyboard
    Period = 'Period', // .> on a US keyboard
    Quote = 'Quote', // '" on a US keyboard
    Semicolon = 'Semicolon', // ;: on a US keyboard
    Slash = 'Slash', // /? on a US keyboard
    Space = 'Space', // Space
}